### ISSUE TITLE
Undefined property: $app

### ISSUE THREAD

**Issue by eane** [willvincent/feeds#1]

**Comment by willvincent** [comment]
Depends on where you're trying to use it I suppose.  In the routes.php file for a laravel 5 project, 
`$this->app->make('Feeds')` should return a simplepie object.

I am thinking about building this out with a facade so that instead you could simply do something like this:

```
$feed = Feed::url('/rss-feed-url-here/');
```

But I'm still very new to laravel, so I don't know how quickly any of that will progress.  Presently all this does is bind 'Feeds' in the IoC container to an instance of SimplePie().

**Comment by willvincent** [comment]
Try `App::make('Feeds')` that should work anywhere in your codebase.

**Comment by willvincent** [comment]
I've added a facade, and updated the readme. Should be easy to use now.
