### ISSUE TITLE
No feeds are returned

### ISSUE THREAD

**Issue by milanchheda** [willvincent/feeds#33]
Hey,

I installed this package without any errors and my application was working fine. Today, I setup my laravel application on another laptop and everything works fine except that no feeds are returned and no errors too :(

I am clueless where to check, as there is nothing in laravel.log nor in my server logs. Any idea, why is it failing and not returning any feeds? Where should I be checking for logs? 

I am running the below code and getting no results: 

```
$feed = Feeds::make('http://blog.case.edu/news/feed.atom');
$data = array(
  'title'     => $feed->get_title(),
  'permalink' => $feed->get_permalink(),
  'items'     => $feed->get_items(),
);

print_r($data);

Array
(
    [title] => 
    [permalink] => 
    [items] => Array
        (
        )
)

```

```composer require "simplepie/simplepie ~1.4.1"```

Installed Simplepie too, but still not working. :(

**Comment by milanchheda** [comment]
@willvincent  - Any update here?

**Comment by arie-piscator** [comment]
I had the same issue, the following solution could work for you as well, @milanchheda 

After dumping `$feed` I saw this error:
> XML or PCRE extensions not loaded! 

I hope you will see an error as well. If it is the same error, you can resolve this by installing php-xml and restarting your web server. PCRE is probably loaded, since it is a core PHP extension.
